// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SpaceWeather.Domain.Context;

#nullable disable

namespace SpaceWeather.Bootstrap.Migrations
{
    [DbContext(typeof(SpaceWeatherDbContext))]
    [Migration("20230922203543_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("SpaceWeather.Domain.Models.MagneticIndexReading", b =>
                {
                    b.Property<DateTimeOffset>("StartTimeUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Type")
                        .HasColumnType("char(1)");

                    b.Property<byte>("Station")
                        .HasColumnType("tinyint unsigned");

                    b.Property<DateTimeOffset>("EndTimeUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<double>("Value")
                        .HasPrecision(3, 2)
                        .HasColumnType("double");

                    b.HasKey("StartTimeUtc", "Type", "Station");

                    b.ToTable("MagneticIndexReadings", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
