version: '3.4'

services:
  spaceweather.sync:
    environment:
      DOTNET_ENVIRONMENT: Development

  spaceweather.bootstrap:
    environment:
      DOTNET_ENVIRONMENT: Development

  spaceweather.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  spaceweather.db:
    environment:
      MARIADB_ROOT_PASSWORD: spaceweather_root
      MARIADB_PASSWORD: spaceweather_dev
    ports:
      - 3306:3306
